name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Create stuff...
      run: mkdir out && echo test v2 > out/test.txt
    - name: Publish update site to https://raw.githubusercontent.com/howlger/Playground-Update-Site/update
      env:
      
        # Requires the following:
        # 1. Create a new personal access token with the scope "repo > public_repo":
        #    1. In <https://github.com/settings/tokens> click "Generate new token"
        #    2. Enter a name of your choice (e.g. "Update Site <Repository>")
        #    3. Select the scope "repo > public_repo"
        #    4. Click "Generate token"
        #    5. Copy the token value (40-digit hexadecimal number)
        # 2. In the repository containig this workflow add the created token as a secrect
        #    1. In the repository in the "Settings" tab go to "Secrets"
        #    2. Click the link "Add a new secret"
        #    3. Paste the token value (40-digit hexadecimal number)
        #    4. Enter the name "PUBLISH_UPDATE_SITE"
        TOKEN: ${{ secrets.PUBLISH_UPDATE_SITE }}
        
        UPDATE_SITE_PATH: out
        UPDATE_SITE_REPO: howlger/Playground-Update-Site
 
      run: |
        SOURCE_DIR="$(pwd)/${UPDATE_SITE_PATH}"
        TARGET_REPO="https://${GITHUB_ACTOR}:${TOKEN}@github.com/${UPDATE_SITE_REPO}.git"
        mkdir "${HOME}/target_repo"
        cd "${HOME}/target_repo"
        ls -la
        git clone "${TARGET_REPO}" --branch master --depth 1
        cd *
        rm -rf update
        cp -avr "${SOURCE_DIR}" update
        pwd
        ls -la
        ls -la update
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name  "${GITHUB_ACTOR}"
        git add update
        git commit -m "Update Eclipse update site"
        echo Pushing...
        git push "${TARGET_REPO}" HEAD:master
