name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: ls -l .
    - run: mkdir out && echo test > out/test.txt
    - run: ls -l out
    - run: ls -la .
    - name: Publish update site to https://raw.githubusercontent.com/howlger/Playground-Update-Site/update
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLISH_UPDATE_SITE }}
      run: |
        SOURCE_DIR="$(pwd)/out"
        REMOTE="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/howlger/Playground-Update-Site.git"
        mkdir "${HOME}/target_repo"
        cd "${HOME}/target_repo"
        ls -la
        git clone ${REMOTE} --branch master --depth 1
        cd *
        rm -rf update
        cp -avr "${SOURCE_DIR}" update
        ls -la
        ls -la update
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name  "${GITHUB_ACTOR}"
        git add update
        git commit -m "Update Eclipse update site"
        echo Pushing...
        git push origin master
