name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: mkdir out && echo test > out/test.txt
    - run: ls -l out
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: howlger/Playground-Update-Site
        branch: master
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        github_pat: '${{ secrets.PUBLISH_UPDATE_SITE }}'
        source_folder: out
