name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: ls -l .
    - run: mkdir out && echo test > out/test.txt
    - run: ls -l out
    - run: ls -la .
    - run: pwd
    - run: |
        mkdir out2
        echo test2 > out2/test2.txt
        cd out2
        ls -la
    - run: |
        FOO="Hello World"
        echo ${FOO}
        echo ${HOME}
        cd "${HOME}"
        pwd
