name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: mkdir out123 && echo test > out123/test.txt
    - run: ls -l out123
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: howlger/Playground-Update-Site
        branch: master
        github_token: '${{ secrets.GITHUB_TOKEN }}'
        github_pat: '${{ secrets.PUBLISH_UPDATE_SITE }}'
        source_folder: out123
        commit_message: Publish update site
        working_directory: target_repo
        target_folder: out1234
    - run: ls -l target_repo
    - run: ls -l target_repo/out1234
