name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: ls -l .
    - run: mkdir out && echo test > out/test.txt
    - run: ls -l out
    - run: ls -la .
    - run: |
        SOURCE_DIR=$(pwd)
        echo ${SOURCE_DIR}
        echo $(pwd)/path/to/dir
        SOURCE_DIR2="$(pwd)/path/to/dir"
        echo ${SOURCE_DIR2}
    - run: |
        FOO="Hello World"
        echo ${FOO}
        echo ${HOME}
        pwd
        cd "${HOME}"
        pwd
